#!/bin/bash
# Configure iptables firewall

# Limit PATH
PATH="/sbin:/usr/sbin:/bin:/usr/bin"

# iptables configuration
firewall_start() {

  # Drop invalid packets
  iptables -A INPUT -m conntrack --ctstate INVALID -j chain-incoming-log-and-drop

  # Accept everything on loopback
  iptables -A INPUT  -i lo -j ACCEPT
  iptables -A OUTPUT -o lo -j ACCEPT

  # ACCEPT incoming packets for established connections
  iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

  # Accept incoming ICMP
  iptables -A INPUT -p icmp -j ACCEPT

  # Accept incoming SSH
  iptables -A INPUT -p tcp --dport 22 -j chain-incoming-ssh

  # Accept outgoing packets for established connections
  iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

  # Accept outgoing DNS
  iptables -A INPUT -p tcp --dport 25 -j ACCEPT 
  iptables -A OUTPUT -p tcp --dport 25 -j ACCEPT
  iptables -A INPUT -p tcp --dport 80 -j ACCEPT
  iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
  iptables -A INPUT -p tcp --dport 443 -j ACCEPT
  iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
  iptables -A INPUT -p tcp --dport 587 -j ACCEPT
  iptables -A OUTPUT -p tcp --dport 587 -j ACCEPT
  iptables -A INPUT -p tcp --dport 993 -j ACCEPT
  iptables -A OUTPUT -p tcp --dport 993 -j ACCEPT
  iptables -A INPUT -p tcp --dport 22345 -j ACCEPT
  iptables -A OUTPUT -p tcp --dport 22345 -j ACCEPT

  iptables -A INPUT -p tcp --dport 53 -j ACCEPT
  iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT
  iptables -A INPUT -p udp --dport 53 -j ACCEPT
  iptables -A OUTPUT -p udp --dport 53 -j ACCEPT

  # Accept outgoing NTP
  iptables -A OUTPUT -p tcp --dport 123 -j ACCEPT
  iptables -A OUTPUT -p udp --dport 123 -j ACCEPT

  # Accept outgoing HTTP/S
  iptables -A OUTPUT -p tcp --dport 80  -j ACCEPT
  iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT

  # Accept outgoing SSH
  iptables -A OUTPUT -p tcp --dport 22  -j ACCEPT

  # Accept outgoing ICMP
  iptables -A INPUT -p icmp -j ACCEPT
  iptables -A OUTPUT -p icmp -j ACCEPT

  # Accept networks
  iptables -A INPUT -s 10.0.0.0/8 -j ACCEPT
  iptables -A OUTPUT -s 10.0.0.0/8 -j ACCEPT
  iptables -A INPUT -s 172.16.0.0/16 -j ACCEPT
  iptables -A OUTPUT -s 172.16.0.0/16 -j ACCEPT
  iptables -A INPUT -s 192.168.255.0/24 -j ACCEPT
  iptables -A OUTPUT -s 192.168.255.0/24 -j ACCEPT
  iptables -A INPUT -s 193.191.177.1 -j ACCEPT
  iptables -A OUTPUT -s 193.191.177.1 -j ACCEPT	
  iptables -A INPUT -s 193.191.177.6 -j ACCEPT
  iptables -A OUTPUT -s 193.191.177.6 -j ACCEPT
  iptables -A INPUT -s 2001:6a8:2880:a021::6 -j ACCEPT
  iptables -A OUTPUT -s 2001:6a8:2880:a021::6 -j ACCEPT

  # Drop everything else
  iptables -P INPUT   DROP
  iptables -P FORWARD DROP
  iptables -P OUTPUT  DROP
}

# clear iptables configuration
firewall_stop() {
  iptables -F
  iptables -X
  iptables -P INPUT   ACCEPT
  iptables -P FORWARD ACCEPT
  iptables -P OUTPUT  ACCEPT
}

# execute action
case "$1" in
  start|restart)
    echo "Starting firewall"
    firewall_stop
    firewall_start
    ;;
  stop)
    echo "Stopping firewall"
    firewall_stop
    ;;
esac
